name: CI
on: [push]
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: run script
        run: |
         scp ./bin/deploy.sh ${SSH_USER}@${SSH_HOST}:/etc/nginx/planetts/
         ssh staging 'cd /etc/nginx/planetts/ && ./deploy.sh'
        env:
          SSH_USER: "ec2-user"
          SSH_KEY: ${{ secrets.EC2_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
