name: CI
on: [push]
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: "ec2-user"
          SSH_KEY: ${{ secrets.EC2_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: run script
        run: |
         sudo scp -o StrictHostKeyChecking=no -r ./bin/deploy.sh ${SSH_USER}@$ec2-54-148-28-57.us-west-2.compute.amazonaws.com://etc/nginx/planetts/
         sudo ssh staging 'cd /etc/nginx/planetts/ && ./deploy.sh'
        env:
          SSH_USER: "ec2-user"
          SSH_KEY: ${{ secrets.EC2_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
